name: foreastro
description: "Fore Astro App Bonwic"
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  phone_input: any
  otp_text_field: ^1.1.3
  animated_custom_dropdown: ^3.0.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  stylish_bottom_bar: ^1.1.0
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  flutter_sizer: ^1.0.5
  gap: ^3.0.1
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.1.3+2
  dio: ^5.4.2+1
  logger: ^2.2.0
  shared_preferences: ^2.2.2
  file_picker: ^8.0.6
  flexible_grid_view: ^0.0.2
  get: ^4.6.6
  card_swiper: ^3.0.1
  zego_uikit_prebuilt_call: ^4.16.12
  zego_uikit_signaling_plugin: ^2.8.2
  firebase_messaging: ^14.9.2
  custom_rating_bar: ^2.0.5
  intl: ^0.19.0
  youtube_player_flutter: ^9.0.1
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  # call function
  zego_zim: ^2.16.0+4
  zego_zimkit: ^1.18.10
  flutter_dotenv: ^5.1.0
  # device_info_plus: ^9.1.0
  socket_io_client: ^2.0.3+1
  http: ^1.2.0
  razorpay_flutter: ^1.3.0
  video_player: ^2.8.6
  quickalert: ^1.1.0
  chewie: ^1.8.1
  translator: ^1.0.0
  zego_uikit_prebuilt_live_streaming: ^3.13.5
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  flutter_launcher_icons: ^0.13.1
  geolocator: ^12.0.0
  zego_uikit_prebuilt_video_conference: ^2.8.5
  google_places_autocomplete_text_field: ^0.1.3
  sms_autofill: ^2.4.1
  buttons_tabbar: ^1.3.13
  change_app_package_name: ^1.3.0
  flutter_tawk: ^0.1.0
  pin_code_fields: ^8.0.1
  restart: ^1.0.0+1
  flutter_widget_from_html_core: ^0.15.2
  onesignal_flutter: ^5.2.5
  path_provider: ^2.1.5
  another_telephony: ^0.3.0
  just_audio: ^0.9.38
  flutter_cached_pdfview: ^0.4.3
  photo_view: ^0.15.0
  package_info_plus: ^8.1.3
  score_progress_pretty_display: ^1.0.5
  # circle_progress_bar: ^0.1.3
  in_app_update: ^4.2.3
  interactive_bottom_sheet: ^1.0.0
  
  
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  firebase_analytics: ^10.10.0
flutter_icons:
  android: "launcher_icon" 
  image_path: "assets/astro.png" 
  # android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/bg/
    - assets/icons/
    - assets/logo/
    - assets/icons/tiny/
    - assets/icons/bottambar/
    


