name: foreastro
description: "Fore Astro App Bonwic"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  otp_text_field: ^1.1.3
  animated_custom_dropdown: ^3.0.0
  fluttertoast: ^8.2.12
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  file_picker: ^10.1.2
  dotted_border: ^2.1.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  provider: ^6.1.2
  firebase_messaging: ^16.0.1
  awesome_notifications: ^0.10.1
  zego_zim: ^2.21.1+2
  zego_zimkit: ^1.19.6
  zego_uikit_prebuilt_call: ^4.18.0
  zego_uikit_prebuilt_live_streaming: ^3.14.5
  flutter_cached_pdfview: ^0.4.2
  photo_view: ^0.15.0
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^12.0.1
  socket_io_client: ^2.0.3+1
  quickalert: ^1.1.0
  just_audio: ^0.10.5
  localstorage: ^5.0.0
  coupon_uikit: ^0.2.1
  uuid: ^4.4.0
  url_launcher: ^6.3.0
  buttons_tabbar: ^1.3.13
  onesignal_flutter: ^5.2.5
  pin_code_fields: ^8.0.1
  http: ^1.2.2
  intl: ^0.20.2
  package_info_plus: ^8.1.3
  in_app_update: ^4.2.3
  workmanager: ^0.9.0+3
  webview_flutter:
  flutter_callkit_incoming: ^2.5.5
  zego_express_engine: ^3.22.0
  google_fonts:
#  phone_input: any
  carousel_slider: ^5.0.0
  stylish_bottom_bar: ^1.1.0
#  country_state_city_pro:
  flutter_sizer: ^1.0.5
  gap: ^3.0.1
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.1.3+2
  dio: ^5.9.0
  flexible_grid_view: ^0.0.2
  get: ^4.6.6
  card_swiper: ^3.0.1
  zego_uikit_signaling_plugin: ^2.8.17
  custom_rating_bar: ^3.0.0
  youtube_player_flutter: ^9.0.1
  flutter_dotenv: ^6.0.0
  razorpay_flutter: ^1.4.0
  video_player: ^2.8.6
  chewie: ^1.8.1
  translator: ^1.0.0
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^7.0.1
  geolocator: ^14.0.2
  zego_uikit_prebuilt_video_conference: ^2.10.2
  google_places_autocomplete_text_field: ^2.0.3
  sms_autofill: ^2.4.1
  change_app_package_name: ^1.3.0
#  flutter_tawk: ^0.1.0
  restart: ^1.0.0+1
  flutter_widget_from_html_core: ^0.17.0
  path_provider: ^2.1.5
#  another_telephony: ^0.3.0
  score_progress_pretty_display: ^1.0.5
  interactive_bottom_sheet: ^1.0.0
  connectivity_plus: ^6.1.2
#  webview_flutter:
  audioplayers: ^6.1.0
  flutter_volume_controller: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  firebase_analytics: ^12.0.1
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/astro.png"
  # android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/bg/
    - assets/icons/
    - assets/logo/
    - assets/icons/tiny/
    - assets/icons/bottambar/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf


