// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsT7xnQ0Kt77BZZF3UQ-uuP1TyKUOy_ak',
    appId: '1:683196372486:android:89a415dbb642a146b15587',
    messagingSenderId: '683196372486',
    projectId: 'astro-99c72',
    storageBucket: 'astro-99c72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBapezBkv9fUN-4NFw44A-dflIA2Mpw3JM',
    appId: '1:683196372486:ios:0f4de2a6d7bdba68b15587',
    messagingSenderId: '683196372486',
    projectId: 'astro-99c72',
    storageBucket: 'astro-99c72.appspot.com',
    androidClientId: '683196372486-1id05d3drs86huk81nnnek4iupjjm7ga.apps.googleusercontent.com',
    iosClientId: '683196372486-p2e2v4v1pn5ifmd52vbpplf2muqar87t.apps.googleusercontent.com',
    iosBundleId: 'com.foreastro.foreastrouserside',
  );

}